name: Learning-iOS
options:
  minimumXcodeGenVersion: "2.6.0"
  bundleIdPrefix: "keijumt.learning.ios"
  deploymentTarget:
    iOS: "13.0"
configs:
  Debug: debug
  Release: release
settings:
  base:
    SWIFT_VERSION: "5.1"
    CODE_SIGN_STYLE: "Automatic"
    TARGETED_DEVICE_FAMILY: "1"
targets:
  Learning-iOS:
    type: application 
    platform: iOS
    sources:
      - path: Learning-iOS
    dependencies:
      - carthage: RxSwift
      - carthage: RxCocoa
      - carthage: RxRelay
      - carthage: APIKit
  Learning-iOSTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Learning-iOSTests
    dependencies:
      - target: Learning-iOS
      - carthage: RxSwift
      - carthage: APIKit
      - carthage: RxCocoa
      - carthage: RxBlocking
      - carthage: RxTest
